
#ifndef _COLOR_PAIRS_H_
#define _COLOR_PAIRS_H_

#ifndef WIN32
#include <ncurses.h>
#else
#include "curses.h"
#endif

enum PairNames {
	WHITE_ON_BLACK = 1,
	RED_ON_BLACK = 2,
	YELLOW_ON_BLACK = 3,
	GREEN_ON_BLACK = 4,
	BLUE_ON_BLACK = 5,
	CYAN_ON_BLACK = 6,
	MAGENTA_ON_BLACK = 7,
	BLACK_ON_YELLOW = 8
};

#define WHITE (COLOR_PAIR(WHITE_ON_BLACK))
#define WHITE_BOLD (A_BOLD | COLOR_PAIR(WHITE_ON_BLACK))

#define RED (COLOR_PAIR(RED_ON_BLACK))
#define RED_BOLD (A_BOLD | COLOR_PAIR(RED_ON_BLACK))

#define YELLOW (COLOR_PAIR(YELLOW_ON_BLACK))
#define YELLOW_BOLD (A_BOLD | COLOR_PAIR(YELLOW_ON_BLACK))

#define GREEN (COLOR_PAIR(GREEN_ON_BLACK))
#define GREEN_BOLD (A_BOLD | COLOR_PAIR(GREEN_ON_BLACK))

#define BLUE (COLOR_PAIR(BLUE_ON_BLACK))
#define BLUE_BOLD (A_BOLD | COLOR_PAIR(BLUE_ON_BLACK))

#define CYAN (COLOR_PAIR(CYAN_ON_BLACK))
#define CYAN_BOLD (A_BOLD | COLOR_PAIR(CYAN_ON_BLACK))

#define MAGENTA (COLOR_PAIR(MAGENTA_ON_BLACK))
#define MAGENTA_BOLD (A_BOLD | COLOR_PAIR(MAGENTA_ON_BLACK))

#define BLACK_ON_YELLOW (COLOR_PAIR(BLACK_ON_YELLOW))
#define BLACK_ON_YELLOW_BOLD (A_BOLD | COLOR_PAIR(BLACK_ON_YELLOW))

class ColorPairs {
public:
	static void InitializePairs();
};

#endif
